#!/bin/bash
# Generate the encryption INTEROP fixture matrix used by the password/encryption
# issues #373 (object key / user unlock), #379 (empty-user unlock) and #380
# (owner-password R5/R6).
#
# Producer: qpdf (external, spec-conforming) — the point is interoperability with
# a conforming implementation, so fixtures must NOT be produced by oxidize-pdf.
#
# Related fixture generators (do not confuse / do not delete as "redundant"):
#   - generate_r5_r6_pdfs.sh                     qpdf,  base=Cold_Email_Hacks.pdf,
#                                                names=encrypted_aes256_r5/r6_*.
#                                                Older, R5/R6 only. This script
#                                                supersedes it for R5/R6 coverage.
#   - tools/scripts/generate_pypdf_encrypted.py  pypdf, names=encrypted_pypdf_*.
#                                                Kept as the cross-PRODUCER check
#                                                (second independent implementation)
#                                                for AES-256/R6.
#
# Base document: interop_base.pdf, generated by
#   cargo run --example gen_encryption_interop_base
# It carries the marker OXIDIZE_INTEROP_FIXTURE_MARKER_V1, which decryption tests
# assert to prove real content was recovered (not just that the file opened).
#
# Matrix: {rc4-40, rc4-128, aes128, aes256r5, aes256r6} x {user, empty}
#         plus {aes256r5, aes256r6} x {unicode}
#         plus {rc4-128, aes128}   x {ctm_user, ctm_empty}
#   user    : user password 'userpw', owner password 'ownerpw'  (distinct)
#   empty   : user password ''       , owner password 'ownerpw'
#   unicode : non-ASCII user + owner passwords (exercises SASLprep normalization,
#             the usual R5/R6 interop break; foco de #380)
#   ctm     : EncryptMetadata=false (cleartext metadata, qpdf upgrades to R4);
#             reproduces #379 — Algorithm 2 must append 0xFFFFFFFF to the key MD5
# The 'empty' files reproduce #379 (empty-user auto-unlock). Every file has a
# distinct non-empty owner password, so owner-unlock (#380) is testable on all.
#
# Requires: qpdf 11.0+ (R5/R6 support) and pdftotext (poppler-utils) for the
# content-recovery check.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! command -v qpdf >/dev/null 2>&1; then
    echo "ERROR: qpdf not found in PATH. Install qpdf 11.0.0+ (R5/R6 support)."
    exit 1
fi
QPDF_MAJOR=$(qpdf --version | head -1 | grep -oE '[0-9]+' | head -1)
if [ "${QPDF_MAJOR:-0}" -lt 11 ]; then
    echo "ERROR: qpdf 11.0.0+ required (R5/R6). Found: $(qpdf --version | head -1)"
    exit 1
fi
if ! command -v pdftotext >/dev/null 2>&1; then
    echo "ERROR: pdftotext not found in PATH. Install poppler-utils."
    exit 1
fi

BASE="interop_base.pdf"
if [ ! -f "$BASE" ]; then
    echo "ERROR: $BASE not found. Generate it first:"
    echo "  (from crate root) cargo run --example gen_encryption_interop_base"
    exit 1
fi

MARKER="OXIDIZE_INTEROP_FIXTURE_MARKER_V1"
USER_PW="userpw"
OWNER_PW="ownerpw"
UNICODE_USER="contraseña_ñ"
UNICODE_OWNER="dueño_café"

# gen <out> <full qpdf args...>  -- appends "-- $BASE $out". Global flags (e.g.
# --allow-weak-crypto for RC4) must precede --encrypt, per qpdf's grammar.
gen() {
    local out="$1"; shift
    qpdf "$@" -- "$BASE" "$out"
    echo "  wrote $out"
}

echo "Generating encryption interop matrix from $BASE ..."

# --- user-password variants (user != owner) ---
gen interop_qpdf_rc4-40_user.pdf    --allow-weak-crypto --encrypt "$USER_PW" "$OWNER_PW" 40
gen interop_qpdf_rc4-128_user.pdf   --allow-weak-crypto --encrypt "$USER_PW" "$OWNER_PW" 128 --use-aes=n
gen interop_qpdf_aes128_user.pdf    --encrypt "$USER_PW" "$OWNER_PW" 128 --use-aes=y
gen interop_qpdf_aes256r5_user.pdf  --encrypt "$USER_PW" "$OWNER_PW" 256 --force-R5
gen interop_qpdf_aes256r6_user.pdf  --encrypt "$USER_PW" "$OWNER_PW" 256

# --- empty-user variants (user = "", owner set) ---
gen interop_qpdf_rc4-40_empty.pdf   --allow-weak-crypto --encrypt "" "$OWNER_PW" 40
gen interop_qpdf_rc4-128_empty.pdf  --allow-weak-crypto --encrypt "" "$OWNER_PW" 128 --use-aes=n
gen interop_qpdf_aes128_empty.pdf   --encrypt "" "$OWNER_PW" 128 --use-aes=y
gen interop_qpdf_aes256r5_empty.pdf --encrypt "" "$OWNER_PW" 256 --force-R5
gen interop_qpdf_aes256r6_empty.pdf --encrypt "" "$OWNER_PW" 256

# --- unicode-password variants (non-ASCII user + owner; SASLprep, #380) ---
gen interop_qpdf_aes256r5_unicode.pdf --encrypt "$UNICODE_USER" "$UNICODE_OWNER" 256 --force-R5
gen interop_qpdf_aes256r6_unicode.pdf --encrypt "$UNICODE_USER" "$UNICODE_OWNER" 256

# --- cleartext-metadata variants (EncryptMetadata=false; #379) ---
# qpdf upgrades these to V4/R4. Algorithm 2 must append 0xFFFFFFFF to the key
# MD5 when metadata is not encrypted; a reader that skips it derives the wrong
# key and fails to unlock even the empty user password. RC4 and AES ciphers,
# empty and non-empty user, all under R4.
gen interop_qpdf_rc4-128_ctm_empty.pdf --allow-weak-crypto --encrypt "" "$OWNER_PW" 128 --use-aes=n --cleartext-metadata
gen interop_qpdf_rc4-128_ctm_user.pdf  --allow-weak-crypto --encrypt "$USER_PW" "$OWNER_PW" 128 --use-aes=n --cleartext-metadata
gen interop_qpdf_aes128_ctm_empty.pdf  --encrypt "" "$OWNER_PW" 128 --use-aes=y --cleartext-metadata
gen interop_qpdf_aes128_ctm_user.pdf   --encrypt "$USER_PW" "$OWNER_PW" 128 --use-aes=y --cleartext-metadata

echo ""
echo "=== Verifying revision (R) per file ==="
for f in interop_qpdf_*.pdf; do
    printf '%-38s ' "$f"
    qpdf --show-encryption "$f" 2>/dev/null | grep -E '^R =' | tr '\n' ' '
    echo ""
done

# Content check: decrypt with the documented password and confirm the marker is
# recovered by an INDEPENDENT reader (poppler), not just that qpdf reports a
# scheme. Catches a silently-broken unlock if passwords/flags drift.
echo ""
echo "=== Verifying marker recovery (poppler pdftotext) ==="
check_marker() { # <file> <password-flag-args...>
    local f="$1"; shift
    if pdftotext "$@" "$f" - 2>/dev/null | grep -q "$MARKER"; then
        echo "  OK   $f"
    else
        echo "  FAIL $f (marker not recovered)"; exit 1
    fi
}
for c in rc4-40 rc4-128 aes128 aes256r5 aes256r6; do
    check_marker "interop_qpdf_${c}_user.pdf"  -upw "$USER_PW"
    check_marker "interop_qpdf_${c}_empty.pdf"
done
check_marker interop_qpdf_aes256r5_unicode.pdf -upw "$UNICODE_USER"
check_marker interop_qpdf_aes256r6_unicode.pdf -upw "$UNICODE_USER"
for c in rc4-128 aes128; do
    check_marker "interop_qpdf_${c}_ctm_user.pdf"  -upw "$USER_PW"
    check_marker "interop_qpdf_${c}_ctm_empty.pdf"
done

echo ""
echo "All fixtures generated and content-verified."
echo "Passwords: user='$USER_PW' owner='$OWNER_PW' (empty: user=''); unicode: user='$UNICODE_USER' owner='$UNICODE_OWNER'"
